from dataclasses import dataclass
from typing import Dict, List

from language.parsing.ast.high_level_structure.high_level_tree import HighLevelTree
from language.parsing.ast.actions.action_block.action_block import ActionBlock
from language.parsing.ast.parsed_node_interface import ParsedNode


@dataclass
class ScriptTree(ParsedNode):
    """ The root node of the tree representation of a Sift script.  
    *#! Implements the ParsedNode interface.*
    """  # noqa: W291

    targets: Dict[str, str]
    """ Simple representation of the targets defined at the start of the script. """
    action_blocks: List[ActionBlock]
    """ The first child of the script tree, containing all the action blocks. """

    @staticmethod
    def _parse_action_blocks_to_dataclasses(action_block_list: List[Dict[str, str]]):
        """ A helper method for parsing raw action block content into ActionBlock instances.

        This method is called by the generate() factory method to transform a list of action block representations,
        which are dictionaries provided by HighLevelTree, into real ActionBlock instances.

        Args:
            action_block_list (List[Dict[str, str]]):
                The list of action blocks, represented rawly by dictionaries where the target is the key
                and the value is the raw content of the action block, to be parsed by ActionBlock's generate() method.

        Returns:
            List[ActionBlock]: The list of ActionBlock instances generated from the raw list of strings.
        """
        instance_action_block_list = []
        for action_block in action_block_list:
            parsed_block = ActionBlock.generate(action_block)
            instance_action_block_list.append(parsed_block)
        return instance_action_block_list

    @classmethod
    def generate(cls, abstract_tree: HighLevelTree):
        """ ScriptTree's factory method.

        Implemented from ParsedNode's generate().
        Given a HighLevelTree object containing raw information about the script,
        generate() stores the targets field as-is in its targets member, and uses
        the ActionBlock class with the _parse_action_blocks_to_dataclasses() static
        helper method to generate child ActionBlock nodes.

        Args:
            abstract_tree (HighLevelTree):
                An instance of HighLevelTree, a skeleton of raw content
                used in the generation of the ScriptTree

        Returns:
            ScriptTree: The instance generated by the factory method.
        """
        targets = abstract_tree.targets
        action_blocks = abstract_tree.actions
        instance_action_block_list = ScriptTree._parse_action_blocks_to_dataclasses(
            action_block_list=action_blocks
        )
        return cls(
            targets=targets,
            action_blocks=instance_action_block_list
        )

    def validate(self) -> bool:
        """ Validates that the necessary components for the ScriptTree class are present after construction.

        The only requirement for the ScriptTree currently follows the requirements outlined for the Sift language.
        It is acceptable if there are no ActionBlocks defined yet; however, at least a list of Targets are expected.

        Returns:
            bool: True if the instance passes validation, False otherwise.
        """
        if not self.targets:
            # While we will accept an empty ActionBlocks list, we cannot accept an empty targets list.
            return False
        return True

    def __str__(self):
        lines = []
        lines.append("ScriptTree:")

        # Print Targets
        lines.append("  Targets:")
        for name, url in self.targets.items():
            lines.append(f"    - {name}: {url}")

        # Print Action Blocks
        lines.append("  Action Blocks:")
        for i, block in enumerate(self.action_blocks, start=1):
            lines.append(f"    {i}. {block.pretty_print(indent=6)}")

        return "\n".join(lines)
